#!/bin/zsh -f

usage () {
  cat <<EOF
usage: $1 [-h] [-f FORMAT] FILE [FILE...]
EOF
  exit 1
}

while getopts 'hf:' c; do
  case $c in
    h) usage $0;;
    f) fmt=$OPTARG;;
  esac
done 

shift $((OPTIND - 1))

(( $# > 0 )) || usage $0

if [[ $fmt ]]; then
  var="\"$fmt\""
else
  var=nil
fi

for f in "$@"; do
    e=$(<<EOF
(progn
  (add-to-list 'load-path "${0:a:h}")
  (require 'org-export)
  (let ((my/org-export-fmt $var))
    (my/org-export-file "$f")))
EOF
     )
    emacs --batch -Q --eval="$e" --kill
done
